### ISSUE TITLE
Functions results not identical for input value 21 degrees

### ISSUE THREAD

**Issue by cclauss** [cclauss/compass-direction-bakeoff#1]
We get an assertion error here...

(21, 'NE', 'N', 'N', 'NE', 'NE', 'NE', 'NE')

**Comment by jldiaz** [comment]
This would be the first one... since the assertion causes the interruption of the execution. If you remove the assertion and, instead, print the values for which the functions do not agree, you'll get:

```
(21, 'NE', 'N', 'N', 'NE', 'NE', 'NE', 'NE')
(22, 'NE', 'N', 'N', 'NE', 'NE', 'NE', 'NE')
(68, 'NE', 'E', 'E', 'NE', 'NE', 'NE', 'NE')
(69, 'NE', 'E', 'E', 'NE', 'NE', 'NE', 'NE')
(111, 'SE', 'E', 'E', 'SE', 'SE', 'SE', 'SE')
(112, 'SE', 'E', 'E', 'SE', 'SE', 'SE', 'SE')
(158, 'SE', 'S', 'S', 'SE', 'SE', 'SE', 'SE')
(159, 'SE', 'S', 'S', 'SE', 'SE', 'SE', 'SE')
(201, 'SW', 'S', 'S', 'SW', 'SW', 'SW', 'SW')
(202, 'SW', 'S', 'S', 'SW', 'SW', 'SW', 'SW')
(248, 'SW', 'W', 'W', 'SW', 'SW', 'SW', 'SW')
(249, 'SW', 'W', 'W', 'SW', 'SW', 'SW', 'SW')
(291, 'NW', 'W', 'W', 'NW', 'NW', 'NW', 'NW')
(292, 'NW', 'W', 'W', 'NW', 'NW', 'NW', 'NW')
(338, 'NW', 'N', 'N', 'NW', 'NW', 'NW', 'NW')
(339, 'NW', 'N', 'N', 'NW', 'NW', 'NW', 'NW')
```

However, which function provides the "right" answer? If we have to make all of them agree, which is the "correct" canonical answer for each direction?

If we want to emulate the behaviour of the first function (solution 0), the one given by the OP, then the simple and elegant code of solutions 1 and 2 is not possible, because the solution 0 uses not equally sized octants. Octants in directions N,S,E,W cover 40 degrees (and include both extremes), while octants NE, SE, NW, SW cover 50 degrees (and do not include both extremes).

If we want to unify the output of all the functions, then the only way will be to make solutions 0, 3, 4, 5 and 6 use the same kind of octants than solutions 1 and 2 use.
